# Generated by Django 5.2.7 on 2025-11-25 10:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('infrastructure', '0003_contact_alter_location_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_tag', models.CharField(help_text='Unique identifier/tag for the asset', max_length=100, unique=True)),
                ('model', models.CharField(blank=True, help_text='General model name', max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, help_text='Serial number', max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('in_repair', 'In Repair'), ('disposed', 'Disposed')], default='active', help_text='Asset status', max_length=20)),
                ('purchase_date', models.DateField(blank=True, help_text='Purchase date', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, help_text='MAC address in format XX:XX:XX:XX:XX:XX', max_length=17, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address (IPv4 or IPv6)', null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('system_uuid', models.CharField(blank=True, help_text='System UUID (e.g., from BIOS/UEFI)', max_length=36, null=True)),
                ('system_uptime', models.DurationField(blank=True, help_text='System uptime duration', null=True)),
                ('in_current_state_since', models.DateField(blank=True, help_text='Date when asset entered current state', null=True)),
                ('expected_checkin_date', models.DateField(blank=True, help_text='Expected date for asset check-in', null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price of the asset', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('replacement_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated replacement cost', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('salvage_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated salvage value at end of life', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('useful_life_years', models.PositiveIntegerField(blank=True, help_text='Expected useful life in years', null=True)),
                ('approaching_eol_months', models.PositiveIntegerField(blank=True, help_text='Months before approaching end-of-life', null=True)),
                ('po_number', models.CharField(blank=True, help_text='Purchase Order number', max_length=100, null=True)),
                ('machine_serial_number', models.CharField(blank=True, help_text='Manufacturer serial number', max_length=255, null=True)),
                ('product_number', models.CharField(blank=True, help_text='Product/part number', max_length=255, null=True)),
                ('acquisition_date', models.DateField(blank=True, help_text='Date when asset was acquired', null=True)),
                ('warranty_expiration', models.DateField(blank=True, help_text='Warranty expiration date', null=True)),
                ('installation_date', models.DateField(blank=True, help_text='Date when asset was installed', null=True)),
                ('calendar_alerts', models.BooleanField(default=False, help_text='Enable calendar alerts for this asset')),
                ('additional_details', models.JSONField(blank=True, help_text='Additional custom details in JSON format', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User assigned to this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='assets', to='infrastructure.department')),
                ('location', models.ForeignKey(blank=True, help_text='Physical location of the asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='infrastructure.location')),
                ('managed_by', models.ForeignKey(blank=True, help_text='User responsible for managing this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_managed', to=settings.AUTH_USER_MODEL)),
                ('related_items', models.ManyToManyField(blank=True, help_text='Related assets', to='assets.asset')),
                ('used_by', models.ForeignKey(blank=True, help_text='User currently using this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'assets_asset',
                'ordering': ['name', 'asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(blank=True, help_text='Hex color code for tag display (e.g., #FF5733)', max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Tag',
                'verbose_name_plural': 'Asset Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Lifecycle',
                'verbose_name_plural': 'Custom Lifecycles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tech Specs',
                'verbose_name_plural': 'Tech Specs',
                'db_table': 'assets_tech_specs',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_info', models.TextField(blank=True, help_text='Contact information for the vendor', null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComputerDetails',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='computer_details', serialize=False, to='assets.asset')),
                ('cpu', models.CharField(blank=True, help_text='CPU specification (e.g., Intel Core i7-9700K)', max_length=255, null=True)),
                ('ram', models.CharField(blank=True, help_text='RAM specification (e.g., 16GB DDR4)', max_length=100, null=True)),
                ('storage', models.CharField(blank=True, help_text='Storage specification (e.g., 512GB SSD)', max_length=255, null=True)),
                ('gpu', models.CharField(blank=True, help_text='GPU specification', max_length=255, null=True)),
                ('os', models.CharField(blank=True, help_text='Operating system', max_length=255, null=True)),
                ('processor', models.CharField(blank=True, help_text='Processor specification (e.g., Intel Core i7-9700K)', max_length=255, null=True)),
                ('memory', models.CharField(blank=True, help_text='Memory/RAM specification (e.g., 16GB DDR4)', max_length=100, null=True)),
                ('hard_drive', models.CharField(blank=True, help_text='Hard drive/storage specification (e.g., 512GB SSD)', max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, help_text='Hardware serial number', max_length=255, null=True)),
                ('product_model_number', models.CharField(blank=True, help_text='Product/Model number', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Computer Details',
                'verbose_name_plural': 'Computer Details',
                'db_table': 'assets_computer_details',
            },
        ),
        migrations.CreateModel(
            name='DisplayDetails',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='display_details', serialize=False, to='assets.asset')),
                ('size_inches', models.PositiveIntegerField(blank=True, help_text='Display size in inches', null=True)),
                ('resolution', models.CharField(blank=True, help_text='Resolution (e.g., 1920x1080, 4K)', max_length=50, null=True)),
                ('panel_type', models.CharField(blank=True, help_text='Panel type (e.g., LCD, LED, OLED, IPS)', max_length=50, null=True)),
                ('refresh_rate', models.PositiveIntegerField(blank=True, help_text='Refresh rate in Hz', null=True)),
            ],
            options={
                'verbose_name': 'Display Details',
                'verbose_name_plural': 'Display Details',
                'db_table': 'assets_display_details',
            },
        ),
        migrations.CreateModel(
            name='NetworkDetails',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='network_details', serialize=False, to='assets.asset')),
                ('mac_address', models.CharField(blank=True, help_text='MAC address in format XX:XX:XX:XX:XX:XX', max_length=17, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address (IPv4 or IPv6)', null=True)),
                ('firmware', models.CharField(blank=True, help_text='Firmware version', max_length=255, null=True)),
                ('ports_count', models.PositiveIntegerField(blank=True, help_text='Number of ports', null=True)),
                ('throughput', models.CharField(blank=True, help_text='Throughput specification (e.g., 1Gbps, 10Gbps)', max_length=100, null=True)),
                ('ports', models.CharField(blank=True, help_text='Port specifications (e.g., 24x Gigabit Ethernet, 4x SFP+)', max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, help_text='Hardware serial number', max_length=255, null=True)),
                ('product_model_number', models.CharField(blank=True, help_text='Product/Model number', max_length=255, null=True)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=100, null=True)),
                ('upc', models.CharField(blank=True, help_text='Universal Product Code', max_length=100, null=True)),
                ('mpn', models.CharField(blank=True, help_text='Manufacturer Part Number', max_length=100, null=True)),
                ('cpn', models.CharField(blank=True, help_text='Customer Part Number', max_length=100, null=True)),
                ('ean', models.CharField(blank=True, help_text='European Article Number', max_length=100, null=True)),
                ('gtin', models.CharField(blank=True, help_text='Global Trade Item Number', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Network Details',
                'verbose_name_plural': 'Network Details',
                'db_table': 'assets_network_details',
            },
        ),
        migrations.CreateModel(
            name='PeripheralDetails',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='peripheral_details', serialize=False, to='assets.asset')),
                ('connection_type', models.CharField(blank=True, help_text='Connection type (e.g., USB, Bluetooth, Wireless)', max_length=100, null=True)),
                ('peripheral_type', models.CharField(blank=True, help_text='Peripheral type (e.g., Keyboard, Mouse, Webcam)', max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, help_text='Hardware serial number', max_length=255, null=True)),
                ('product_model_number', models.CharField(blank=True, help_text='Product/Model number', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Peripheral Details',
                'verbose_name_plural': 'Peripheral Details',
                'db_table': 'assets_peripheral_details',
            },
        ),
        migrations.CreateModel(
            name='PhoneDetails',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='phone_details', serialize=False, to='assets.asset')),
                ('connection_interface', models.CharField(blank=True, help_text='Connection interface (e.g., VoIP, Analog, Digital, SIP)', max_length=255, null=True)),
                ('phone_type', models.CharField(blank=True, help_text='Phone type (e.g., Desk Phone, VoIP Phone)', max_length=100, null=True)),
                ('extension', models.CharField(blank=True, help_text='Phone extension number', max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, help_text='Hardware serial number', max_length=255, null=True)),
                ('product_model_number', models.CharField(blank=True, help_text='Product/Model number', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Phone Details',
                'verbose_name_plural': 'Phone Details',
                'db_table': 'assets_phone_details',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Asset category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetcategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='assets', to='assets.assettag'),
        ),
        migrations.AddField(
            model_name='asset',
            name='custom_lifecycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.customlifecycle'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='tech_specs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='assets.techspecs'),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor/supplier of the asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.vendor'),
        ),
        migrations.CreateModel(
            name='AssetAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='assets/attachments/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Attachment',
                'verbose_name_plural': 'Asset Attachments',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='assets_asse_content_83dbe9_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='assets.asset')),
                ('related_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Relation',
                'verbose_name_plural': 'Asset Relations',
                'unique_together': {('asset', 'related_asset')},
            },
        ),
    ]
