# Generated by Django 5.2.7 on 2025-11-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='assets', to='assets.assettag'),
        ),
    ]
