# Generated by Django 5.2.7 on 2025-11-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['name'], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_tag',
        ),
    ]
