# Generated by Django 5.2.7 on 2025-11-26 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_options_remove_asset_asset_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(help_text='Asset category', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.assetcategory'),
        ),
    ]
