# Generated by Django 5.2.7 on 2025-12-01 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_asset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(blank=True, help_text='Unique identifier/tag for the asset', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='impact',
            field=models.PositiveIntegerField(blank=True, help_text='Impact of the asset', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
