# Generated by Django 5.2.7 on 2025-12-02 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_asset_tag_asset_impact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='additional_details',
        ),
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assets/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Image',
                'verbose_name_plural': 'Asset Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
