# Generated by Django 5.2.7 on 2025-12-03 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_remove_asset_additional_details_assetimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='calendar_alerts',
            new_name='calendar_alerts_enabled',
        ),
        migrations.CreateModel(
            name='CalendarAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date to alert on')),
                ('message', models.TextField(blank=True, help_text='Alert message/description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_alerts', to='assets.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Alert',
                'verbose_name_plural': 'Calendar Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
