# Generated by Django 5.2.7 on 2025-12-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_rename_calendar_alerts_asset_calendar_alerts_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='calendar_alerts_enabled',
        ),
    ]
