# Generated by Django 5.2.7 on 2025-12-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_remove_asset_calendar_alerts_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='related_items',
        ),
    ]
