# Generated by Django 5.2.7 on 2025-12-10 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_remove_asset_related_items'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assetattachment',
            name='assets_asse_content_83dbe9_idx',
        ),
        migrations.RemoveField(
            model_name='assetattachment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='assetattachment',
            name='object_id',
        ),
        migrations.AddField(
            model_name='assetattachment',
            name='asset',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assets.asset'),
            preserve_default=False,
        ),
    ]
