# Generated by Django 5.2.7 on 2026-03-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_assetimage_validators_and_upload_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Asset Report',
                'verbose_name_plural': 'Asset Reports',
                'db_table': 'assets_asset_report',
                'permissions': [('view_operating_system', 'View operating system report'), ('view_applications', 'View applications report'), ('view_availability', 'View availability report'), ('view_location', 'View location report'), ('view_warranty', 'View warranty report'), ('view_model', 'View model report'), ('view_asset_type', 'View asset type report'), ('view_department', 'View department report'), ('view_cost', 'View cost report'), ('view_firmware', 'View firmware report')],
            },
        ),
    ]
