# Generated by Django 5.2.7 on 2026-03-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0012_asset_report_permissions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AssetReport",
        ),
    ]
