"""
Wrapper for the Zabbix ``event.*`` API methods.

Reference: https://www.zabbix.com/documentation/current/en/manual/api/reference/event
"""

from typing import Any

from .transport import ZabbixTransport

# Acknowledge action bitmask constants (can be OR-combined)
ACTION_CLOSE = 1
ACTION_ACKNOWLEDGE = 2
ACTION_MESSAGE = 4
ACTION_CHANGE_SEVERITY = 8
ACTION_UNACKNOWLEDGE = 16
ACTION_SUPPRESS = 32
ACTION_UNSUPPRESS = 64
ACTION_CHANGE_CAUSE = 128


class EventAPI:
    """
    Provides access to Zabbix event retrieval and acknowledgement.

    Obtained via ``ZabbixClient.events``.
    """

    def __init__(self, transport: ZabbixTransport) -> None:
        self._t = transport

    # ------------------------------------------------------------------
    # Read
    # ------------------------------------------------------------------

    def get(self, **params: Any) -> list[dict]:
        """
        Retrieve events (problem occurrences, trigger state changes, etc.).

        Common parameters
        -----------------
        output : list[str] | "extend"
            Fields to return.
        eventids : list[str]
            Filter by event IDs.
        groupids : list[str]
            Return events for hosts in the given groups.
        hostids : list[str]
            Return events for the given hosts.
        objectids : list[str]
            Return events generated by the given trigger IDs.
        source : int
            Event source: ``0`` = trigger, ``1`` = discovery rule,
            ``2`` = active agent autoregistration, ``3`` = internal.
        object : int
            Object type: ``0`` = trigger, ``1`` = discovered host, etc.
        value : int
            Event value: ``0`` = resolved / OK, ``1`` = problem.
        acknowledged : int
            ``1`` — return only acknowledged events.
        suppressed : int
            ``1`` — include suppressed events.
        severities : list[int]
            Filter by severity levels.
        tags : list[dict]
            Tag-based filter, e.g.
            ``[{"tag": "component", "value": "db", "operator": 0}]``.
        time_from : int
            Return events created after this Unix timestamp.
        time_till : int
            Return events created before this Unix timestamp.
        selectAcknowledges : list[str] | "extend"
            Include acknowledge / action records.
        selectHosts : list[str] | "extend"
            Include host objects.
        selectRelatedObject : list[str] | "extend"
            Include the related trigger, discovery rule, etc.
        selectTags : list[str] | "extend"
            Include tag objects.
        limit : int
        sortfield : str | list[str]
            Supported: ``"eventid"``, ``"clock"``.
        sortorder : "ASC" | "DESC"

        Returns
        -------
        list[dict]
        """
        return self._t.request("event.get", params)

    # ------------------------------------------------------------------
    # Write
    # ------------------------------------------------------------------

    def acknowledge(
        self,
        eventids: list[str] | str,
        action: int,
        message: str = "",
        **params: Any,
    ) -> dict:
        """
        Perform an action on one or more events (acknowledge, close, etc.).

        Parameters
        ----------
        eventids:
            Single event ID string or list of event IDs to act on.
        action:
            Bitmask specifying the action(s) to perform.  Combine using
            bitwise OR, e.g. ``ACTION_ACKNOWLEDGE | ACTION_MESSAGE``.
            Use the module-level ``ACTION_*`` constants:

            - ``ACTION_CLOSE`` (1) — close the problem
            - ``ACTION_ACKNOWLEDGE`` (2) — acknowledge the event
            - ``ACTION_MESSAGE`` (4) — add a message (requires *message*)
            - ``ACTION_CHANGE_SEVERITY`` (8) — change severity
            - ``ACTION_UNACKNOWLEDGE`` (16) — remove acknowledgement
            - ``ACTION_SUPPRESS`` (32) — suppress the problem
            - ``ACTION_UNSUPPRESS`` (64) — unsuppress the problem
            - ``ACTION_CHANGE_CAUSE`` (128) — change the cause event

        message:
            Text to add as the acknowledgement message.  Required when
            ``ACTION_MESSAGE`` is included in *action*.
        **params:
            Additional fields: ``severity`` (new severity when using
            ``ACTION_CHANGE_SEVERITY``), ``cause_eventid`` (when using
            ``ACTION_CHANGE_CAUSE``).

        Returns
        -------
        dict
            Contains ``eventids`` — IDs of the affected events.

        Example
        -------
        ::

            from lib.zabbix.events import ACTION_ACKNOWLEDGE, ACTION_MESSAGE

            client.events.acknowledge(
                eventids=["1234", "1235"],
                action=ACTION_ACKNOWLEDGE | ACTION_MESSAGE,
                message="Investigating the issue.",
            )
        """
        if isinstance(eventids, str):
            eventids = [eventids]

        payload: dict[str, Any] = {
            "eventids": eventids,
            "action": action,
            **params,
        }
        if message:
            payload["message"] = message

        return self._t.request("event.acknowledge", payload)
