"""
Wrapper for the Zabbix ``problem.*`` API methods.

Problems are read-only via the API (they are generated by Zabbix internally
from trigger state changes).  Use ``EventAPI.acknowledge`` to acknowledge
or close a problem.

Reference: https://www.zabbix.com/documentation/current/en/manual/api/reference/problem
"""

from typing import Any

from .transport import ZabbixTransport


class ProblemAPI:
    """
    Provides read access to Zabbix problems (active trigger fires).

    Obtained via ``ZabbixClient.problems``.
    """

    def __init__(self, transport: ZabbixTransport) -> None:
        self._t = transport

    def get(self, **params: Any) -> list[dict]:
        """
        Retrieve currently active problems.

        Common parameters
        -----------------
        output : list[str] | "extend"
            Fields to return.  Default returns only ``eventid``,
            ``objectid``, ``clock``, and ``severity``.
        eventids : list[str]
            Filter by event / problem IDs.
        groupids : list[str]
            Return problems for hosts in the given groups.
        hostids : list[str]
            Return problems for the given hosts.
        objectids : list[str]
            Return problems generated by the given trigger IDs.
        source : int
            Problem source type: ``0`` = trigger (default), ``3`` = internal.
        object : int
            Object type: ``0`` = trigger (default).
        acknowledged : int
            ``1`` — return only acknowledged problems.
            ``0`` — return only unacknowledged problems.
        suppressed : int
            ``1`` — include suppressed problems.
        severities : list[int]
            Filter by severity levels (e.g. ``[3, 4, 5]`` for average+).
        tags : list[dict]
            Filter by tags, e.g.
            ``[{"tag": "service", "value": "web", "operator": 0}]``.
        recent : int
            ``1`` — return problems from the last hour (including recently
            resolved).
        time_from : int
            Return problems created after this Unix timestamp.
        time_till : int
            Return problems created before this Unix timestamp.
        selectAcknowledges : list[str] | "extend"
            Include acknowledge operations in the response.
        selectTags : list[str] | "extend"
            Include tag objects.
        selectSuppressionData : list[str] | "extend"
            Include suppression details.
        limit : int
        sortfield : str | list[str]
            Supported: ``"eventid"``, ``"severity"``, ``"clock"``.
        sortorder : "ASC" | "DESC"

        Returns
        -------
        list[dict]
            Problem objects.
        """
        return self._t.request("problem.get", params)
