# Generated by Django 5.2.7 on 2026-07-17 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0013_delete_assetreport'),
        ('ipam', '0007_alter_subnet_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationScriptPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zabbix_script_name', models.CharField(max_length=255, unique=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('auto_execute_allowed', models.BooleanField(default=False, help_text='Auto-execution also requires the agent to report high confidence.')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Remediation Script Policy',
                'verbose_name_plural': 'Remediation Script Policies',
                'ordering': ['zabbix_script_name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zabbix_event_id', models.CharField(max_length=64, unique=True)),
                ('zabbix_host_id', models.CharField(max_length=64)),
                ('host_name', models.CharField(max_length=255)),
                ('trigger_name', models.CharField(max_length=500)),
                ('severity', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('investigating', 'Investigating'), ('remediated', 'Remediated'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='investigating', max_length=20)),
                ('confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='assets.asset')),
                ('resolved_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='ipam.device')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('thinking', 'Thinking'), ('tool_call', 'Tool Call'), ('tool_result', 'Tool Result'), ('final', 'Final Decision')], max_length=20)),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tool_input', models.JSONField(blank=True, null=True)),
                ('tool_output', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='remediation.incident')),
            ],
            options={
                'verbose_name': 'Agent Step',
                'verbose_name_plural': 'Agent Steps',
                'ordering': ['incident', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='RemediationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zabbix_script_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('awaiting_approval', 'Awaiting Approval'), ('executed', 'Executed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='proposed', max_length=20)),
                ('dry_run', models.BooleanField(default=False)),
                ('execution_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Null means the action was executed autonomously by the agent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_remediation_actions', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='remediation.incident')),
            ],
            options={
                'verbose_name': 'Remediation Action',
                'verbose_name_plural': 'Remediation Actions',
                'ordering': ['-created_at'],
                'permissions': [('execute_remediationaction', 'Can execute a proposed remediation action')],
            },
        ),
        migrations.CreateModel(
            name='ZabbixHostLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zabbix_host_id', models.CharField(max_length=64, unique=True)),
                ('zabbix_hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('match_source', models.CharField(choices=[('auto', 'Auto-matched'), ('manual', 'Manually confirmed')], default='auto', max_length=10)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zabbix_host_links', to='assets.asset')),
                ('resolved_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zabbix_host_links', to='ipam.device')),
            ],
            options={
                'verbose_name': 'Zabbix Host Link',
                'verbose_name_plural': 'Zabbix Host Links',
                'ordering': ['zabbix_hostname'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='remediation_status_ff4ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['zabbix_host_id'], name='remediation_zabbix__51a3b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentstep',
            constraint=models.UniqueConstraint(fields=('incident', 'step_number'), name='remediation_agentstep_unique_step'),
        ),
    ]
