# Dockerfile for Next.js app (Staging)
FROM node:18-alpine
WORKDIR /app

ENV PORT=3000

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY package.json package-lock.json* .npmrc* ./
# Install all dependencies including devDependencies for build
RUN npm ci --no-audit --no-fund

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ARG SERVER_API_URL
ENV SERVER_API_URL=${SERVER_API_URL}
ARG NEXTAUTH_URL
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ARG NEXTAUTH_SECRET
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

COPY . .
RUN npm run build
RUN npm prune --production
RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

CMD ["npm", "run", "start"]

