import js from "@eslint/js";
import typescriptEslint from "typescript-eslint";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import prettier from "eslint-config-prettier";
import globals from "globals";

export default typescriptEslint.config(
  // Base JavaScript config
  js.configs.recommended,
  
  // Node scripts (e.g. test-rate-limit.mjs)
  {
    files: ["scripts/**/*.mjs", "scripts/**/*.cjs", "scripts/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.node },
    },
    rules: {
      "no-console": "off",
    },
  },

  // Ignore patterns
  {
    ignores: [
      ".next/**",
      "out/**",
      "build/**",
      "dist/**",
      "node_modules/**",
      "coverage/**",
      "*.config.{js,ts,mjs}",
      "jest.config.js",
      "jest.setup.js",
      "next-env.d.ts",
      "**/openapi.d.ts", // auto-generated by openapi-typescript; do not lint
    ],
  },
  
  // TypeScript config
  ...typescriptEslint.configs.recommended,
  
  // React config
  {
    files: ["**/*.{js,jsx,ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.es2021,
      },
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    plugins: {
      react,
      "react-hooks": reactHooks,
    },
    settings: {
      react: {
        version: "detect",
      },
    },
    rules: {
      // TypeScript rules
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      
      // React rules
      ...react.configs.recommended.rules,
      ...react.configs["jsx-runtime"].rules,
      "react/react-in-jsx-scope": "off", // Not needed in Next.js
      "react/prop-types": "off", // Using TypeScript for prop validation
      "react/no-unescaped-entities": "warn",
      
      // React Hooks rules
      ...reactHooks.configs.recommended.rules,
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      
      // General rules
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "prefer-const": "warn",
      "no-var": "error",
      "no-unused-vars": "off", // Use TypeScript version instead

      // Complexity & size (code quality checklist §1.3)
      "complexity": ["warn", { max: 15 }],
      "max-lines": ["warn", { max: 450, skipBlankLines: true, skipComments: true }],
    },
  },

  // Relax complexity for React components
  {
    files: ["**/*.tsx", "**/*.jsx"],
    rules: {
      "complexity": "off",
    },
  },
  
  // Prettier config (must be last to override other configs)
  prettier
);

