# Generated by Django 5.2.7 on 2025-11-14 08:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'infrastructure_location',
                'ordering': ['city', 'address'],
                'unique_together': {('city', 'address')},
            },
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveIntegerField(help_text='Circuit speed in Mbps', validators=[django.core.validators.MinValueValidator(1)])),
                ('carrier', models.CharField(max_length=255)),
                ('circuit_id', models.CharField(blank=True, help_text='Carrier-provided circuit identifier', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuits', to='infrastructure.location')),
            ],
            options={
                'verbose_name': 'Circuit',
                'verbose_name_plural': 'Circuits',
                'db_table': 'infrastructure_circuit',
                'ordering': ['location', 'carrier'],
            },
        ),
        migrations.CreateModel(
            name='PointOfContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('technical', 'Technical PoC'), ('administrative', 'Administrative PoC')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_of_contact', to='infrastructure.circuit')),
            ],
            options={
                'verbose_name': 'Point of Contact',
                'verbose_name_plural': 'Points of Contact',
                'db_table': 'infrastructure_pointofcontact',
                'ordering': ['circuit', 'contact_type'],
                'unique_together': {('circuit', 'contact_type')},
            },
        ),
    ]
