# Generated by Django 5.2.7 on 2025-12-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_contact_alter_location_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carriercontact',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='carriercontact',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='carriercontact',
            name='city',
        ),
        migrations.RemoveField(
            model_name='carriercontact',
            name='state',
        ),
        migrations.RemoveField(
            model_name='carriercontact',
            name='zip_code',
        ),
    ]
