# Generated by Django 5.2.7 on 2026-04-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0004_remove_carriercontact_address1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("company_name", models.CharField(default="NetSentinel Corp", max_length=255)),
                ("subdomain", models.CharField(default="netsentinel.app", max_length=255)),
                ("company_url", models.URLField(blank=True, default="")),
                (
                    "main_contact",
                    models.EmailField(default="admin@netsentinel.com", max_length=254),
                ),
                ("phone_country", models.CharField(blank=True, default="+1", max_length=8)),
                ("phone_number", models.CharField(blank=True, default="", max_length=30)),
                ("phone_extension", models.CharField(blank=True, default="", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profiles",
                "ordering": ["id"],
            },
        ),
    ]
