# Generated by Django 5.2.7 on 2026-01-07 12:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("infrastructure", "0004_remove_carriercontact_address1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Customer name", max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary contact email",
                        max_length=254,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Primary contact phone", max_length=20, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubnetGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subnet Group",
                "verbose_name_plural": "Subnet Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DNSZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="DNS zone name (e.g., example.com)", max_length=255, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Location associated with this DNS zone",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dns_zones",
                        to="infrastructure.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "DNS Zone",
                "verbose_name_plural": "DNS Zones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subnet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        help_text="Network in CIDR notation (e.g., 192.168.1.0/24 or 2001:db8::/32)",
                        max_length=43,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(\n                (\n                    (25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.\n                    (25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.\n                    (25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.\n                    (25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\n                )\n                \\/(3[0-2]|[12]?[0-9])\n                |\n                (\n                    ([A-Fa-f0-9]{1,4}:){7}[A-Fa-f0-9]{1,4}\n                    |\n                    ([A-Fa-f0-9]{1,4}:){1,7}:\n                    |\n                    :(:[A-Fa-f0-9]{1,4}){1,7}\n                )\n                \\/(12[0-8]|1[01][0-9]|[1-9]?[0-9])\n                )$\n                ",
                                message="Network must be in valid IPv4 or IPv6 CIDR notation (e.g., 192.168.1.0/24 or 2001:db8::/32)",
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "gateway_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="Gateway IP address for this subnet", null=True
                    ),
                ),
                (
                    "nameservers",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of nameserver IP addresses or hostnames",
                        null=True,
                    ),
                ),
                (
                    "is_ipv6",
                    models.BooleanField(default=False, help_text="Whether this is an IPv6 subnet"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="active",
                        help_text="Subnet status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer this subnet is assigned to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subnets",
                        to="ipam.customer",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Location where this subnet is used",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subnets",
                        to="infrastructure.location",
                    ),
                ),
                (
                    "master_subnet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent/master subnet this subnet belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_subnets",
                        to="ipam.subnet",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Subnet group this subnet belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subnets",
                        to="ipam.subnetgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subnet",
                "verbose_name_plural": "Subnets",
                "ordering": ["network"],
            },
        ),
        migrations.CreateModel(
            name="IPAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "address",
                    models.GenericIPAddressField(
                        help_text="IP address (IPv4 or IPv6)", unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("assigned", "Assigned"),
                            ("dhcp", "DHCP"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="available",
                        help_text="IP address status",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subnet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subnet this IP address belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_addresses",
                        to="ipam.subnet",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Address",
                "verbose_name_plural": "IP Addresses",
                "ordering": ["address"],
            },
        ),
        migrations.CreateModel(
            name="VLAN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "vlan_id",
                    models.PositiveIntegerField(
                        help_text="VLAN ID (1-4094)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4094),
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Location where this VLAN is used",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vlans",
                        to="infrastructure.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "VLAN",
                "verbose_name_plural": "VLANs",
                "ordering": ["vlan_id"],
                "unique_together": {("vlan_id", "location")},
            },
        ),
        migrations.AddField(
            model_name="subnet",
            name="vlan",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated VLAN",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subnets",
                to="ipam.vlan",
            ),
        ),
        migrations.CreateModel(
            name="VRF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rd",
                    models.CharField(
                        blank=True,
                        help_text="Route Distinguisher (e.g., 65000:100)",
                        max_length=21,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Location where this VRF is used",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vrfs",
                        to="infrastructure.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "VRF",
                "verbose_name_plural": "VRFs",
                "ordering": ["name"],
                "unique_together": {("name", "location")},
            },
        ),
        migrations.AddField(
            model_name="subnet",
            name="vrf",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated VRF",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subnets",
                to="ipam.vrf",
            ),
        ),
        migrations.CreateModel(
            name="DNSRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Record name (relative to zone or FQDN)", max_length=255
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("AAAA", "AAAA"),
                            ("CNAME", "CNAME"),
                            ("MX", "MX"),
                            ("TXT", "TXT"),
                            ("NS", "NS"),
                            ("PTR", "PTR"),
                            ("SRV", "SRV"),
                        ],
                        help_text="DNS record type",
                        max_length=10,
                    ),
                ),
                ("value", models.TextField(help_text="Record value (content)")),
                (
                    "ttl",
                    models.PositiveIntegerField(default=3600, help_text="Time to live in seconds"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "zone",
                    models.ForeignKey(
                        help_text="DNS zone this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="ipam.dnszone",
                    ),
                ),
            ],
            options={
                "verbose_name": "DNS Record",
                "verbose_name_plural": "DNS Records",
                "ordering": ["zone", "name", "record_type"],
                "unique_together": {("zone", "name", "record_type")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="subnet",
            unique_together={("network", "location")},
        ),
    ]
