# Generated by Django 5.2.7 on 2026-01-08 15:14

import django.core.validators
import django.db.models.deletion
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipam", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subnet",
            name="network",
            field=models.CharField(
                help_text="Network in CIDR notation (e.g., 192.168.1.0/24 or 2001:db8::/32)",
                max_length=43,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(\n                (\n                    (25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.\n                    (25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.\n                    (25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.\n                    (25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\n                )\n                \\/(3[0-2]|[12]?[0-9])\n                |\n                (\n                    ([A-Fa-f0-9]{1,4}:){7}[A-Fa-f0-9]{1,4}\n                    |\n                    ([A-Fa-f0-9]{1,4}:){1,7}:\n                    |\n                    :(:[A-Fa-f0-9]{1,4}){1,7}\n                    |\n                    ([A-Fa-f0-9]{1,4}:){1,6}:[A-Fa-f0-9]{1,4}\n                    |\n                    ([A-Fa-f0-9]{1,4}:){1,5}(:[A-Fa-f0-9]{1,4}){1,2}\n                    |\n                    ([A-Fa-f0-9]{1,4}:){1,4}(:[A-Fa-f0-9]{1,4}){1,3}\n                    |\n                    ([A-Fa-f0-9]{1,4}:){1,3}(:[A-Fa-f0-9]{1,4}){1,4}\n                    |\n                    ([A-Fa-f0-9]{1,4}:){1,2}(:[A-Fa-f0-9]{1,4}){1,5}\n                    |\n                    [A-Fa-f0-9]{1,4}:((:[A-Fa-f0-9]{1,4}){1,6})\n                    |\n                    :((:[A-Fa-f0-9]{1,4}){1,7}|:)\n                )\n                \\/(12[0-8]|1[01][0-9]|[1-9]?[0-9])\n                )$\n                ",
                        flags=re.RegexFlag["VERBOSE"],
                        message="Network must be in valid IPv4 or IPv6 CIDR notation (e.g., 192.168.1.0/24 or 2001:db8::/32)",
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="FavoriteSubnet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subnet",
                    models.ForeignKey(
                        help_text="Subnet that was favorited",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="ipam.subnet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who favorited this subnet",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_subnets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite Subnet",
                "verbose_name_plural": "Favorite Subnets",
                "ordering": ["-created_at"],
                "unique_together": {("user", "subnet")},
            },
        ),
    ]
