# Generated by Django 5.2.7 on 2026-01-10 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0010_remove_assetattachment_assets_asse_content_83dbe9_idx_and_more"),
        ("ipam", "0003_iprequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IPAssignmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("reassigned", "Reassigned"),
                            ("released", "Released"),
                            ("status_changed", "Status Changed"),
                            ("reserved", "Reserved"),
                            ("deprecated", "Deprecated"),
                        ],
                        help_text="Action performed",
                        max_length=20,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True, help_text="Previous IP address status", max_length=20, null=True
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, help_text="New IP address status", max_length=20, null=True
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for this assignment/change", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "IP Assignment History",
                "verbose_name_plural": "IP Assignment Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="iprequest",
            new_name="ipam_iprequ_status_25cefa_idx",
            old_name="ipam_iprequ_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="iprequest",
            new_name="ipam_iprequ_request_dc8817_idx",
            old_name="ipam_iprequ_requested_idx",
        ),
        migrations.RenameIndex(
            model_name="iprequest",
            new_name="ipam_iprequ_subnet__516578_idx",
            old_name="ipam_iprequ_subnet_status_idx",
        ),
        migrations.AddField(
            model_name="ipaddress",
            name="assigned_at",
            field=models.DateTimeField(
                blank=True, help_text="When this IP address was assigned", null=True
            ),
        ),
        migrations.AddField(
            model_name="ipaddress",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who assigned this IP address",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_ip_addresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ipaddress",
            name="assigned_to_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Asset/device this IP address is assigned to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_ip_addresses",
                to="assets.asset",
            ),
        ),
        migrations.AlterField(
            model_name="iprequest",
            name="description",
            field=models.TextField(
                blank=True, help_text="Additional description or notes", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="ipaddress",
            index=models.Index(fields=["status", "subnet"], name="ipam_ipaddr_status_7d4408_idx"),
        ),
        migrations.AddIndex(
            model_name="ipaddress",
            index=models.Index(fields=["assigned_to_asset"], name="ipam_ipaddr_assigne_b4f64a_idx"),
        ),
        migrations.AddField(
            model_name="ipassignmenthistory",
            name="assigned_to_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Asset this IP was assigned to (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ip_assignment_history",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="ipassignmenthistory",
            name="ip_address",
            field=models.ForeignKey(
                help_text="IP address this history entry belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_history",
                to="ipam.ipaddress",
            ),
        ),
        migrations.AddField(
            model_name="ipassignmenthistory",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed this action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ip_assignment_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ipassignmenthistory",
            name="previous_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Previous asset (for reassignments)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_ip_assignments",
                to="assets.asset",
            ),
        ),
        migrations.AddIndex(
            model_name="ipassignmenthistory",
            index=models.Index(
                fields=["ip_address", "-created_at"], name="ipam_ipassi_ip_addr_579ce2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ipassignmenthistory",
            index=models.Index(
                fields=["assigned_to_asset", "-created_at"], name="ipam_ipassi_assigne_542278_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ipassignmenthistory",
            index=models.Index(
                fields=["action", "-created_at"], name="ipam_ipassi_action_ac6cf6_idx"
            ),
        ),
    ]
