# Generated by Django 5.2.7 on 2026-01-15 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0004_remove_carriercontact_address1_and_more"),
        ("ipam", "0004_ipassignmenthistory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DHCPScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="DHCP scope name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Scope description", null=True),
                ),
                (
                    "start_ip",
                    models.GenericIPAddressField(help_text="Starting IP address for the scope"),
                ),
                (
                    "end_ip",
                    models.GenericIPAddressField(help_text="Ending IP address for the scope"),
                ),
                (
                    "subnet_mask",
                    models.GenericIPAddressField(help_text="Subnet mask for the scope"),
                ),
                (
                    "gateway",
                    models.GenericIPAddressField(
                        blank=True, help_text="Default gateway", null=True
                    ),
                ),
                (
                    "dns_servers",
                    models.CharField(
                        blank=True,
                        help_text="DNS servers (comma-separated)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "lease_duration",
                    models.IntegerField(
                        default=86400, help_text="Lease duration in seconds (default: 24 hours)"
                    ),
                ),
                (
                    "max_leases",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of leases (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether the scope is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subnet",
                    models.ForeignKey(
                        help_text="Subnet this DHCP scope belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dhcp_scopes",
                        to="ipam.subnet",
                    ),
                ),
            ],
            options={
                "verbose_name": "DHCP Scope",
                "verbose_name_plural": "DHCP Scopes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DHCPReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(help_text="Reserved IP address")),
                (
                    "mac_address",
                    models.CharField(help_text="MAC address to reserve the IP for", max_length=17),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True,
                        help_text="Hostname for the reservation",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Reservation description", null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the reservation is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.ForeignKey(
                        help_text="DHCP scope this reservation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="ipam.dhcpscope",
                    ),
                ),
            ],
            options={
                "verbose_name": "DHCP Reservation",
                "verbose_name_plural": "DHCP Reservations",
                "ordering": ["ip_address"],
            },
        ),
        migrations.CreateModel(
            name="DHCPLease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(help_text="Leased IP address")),
                (
                    "mac_address",
                    models.CharField(help_text="MAC address of the client", max_length=17),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True, help_text="Client hostname", max_length=255, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("released", "Released"),
                            ("declined", "Declined"),
                        ],
                        default="active",
                        help_text="Lease status",
                        max_length=20,
                    ),
                ),
                ("lease_start", models.DateTimeField(help_text="When the lease started")),
                ("lease_end", models.DateTimeField(help_text="When the lease expires")),
                (
                    "lease_renewal",
                    models.DateTimeField(
                        blank=True, help_text="When the lease was last renewed", null=True
                    ),
                ),
                (
                    "client_identifier",
                    models.CharField(
                        blank=True, help_text="DHCP client identifier", max_length=255, null=True
                    ),
                ),
                (
                    "vendor_class",
                    models.CharField(
                        blank=True, help_text="DHCP vendor class", max_length=255, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.ForeignKey(
                        help_text="DHCP scope this lease belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases",
                        to="ipam.dhcpscope",
                    ),
                ),
            ],
            options={
                "verbose_name": "DHCP Lease",
                "verbose_name_plural": "DHCP Leases",
                "ordering": ["-lease_start"],
            },
        ),
        migrations.CreateModel(
            name="IPPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Pool name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Pool description", null=True),
                ),
                (
                    "start_ip",
                    models.GenericIPAddressField(help_text="Starting IP address in the pool"),
                ),
                ("end_ip", models.GenericIPAddressField(help_text="Ending IP address in the pool")),
                (
                    "reservation_policy",
                    models.CharField(
                        choices=[
                            ("none", "No Reservation"),
                            ("percentage", "Percentage Reserved"),
                            ("fixed", "Fixed Count Reserved"),
                        ],
                        default="none",
                        help_text="Reservation policy for the pool",
                        max_length=50,
                    ),
                ),
                (
                    "reserved_percentage",
                    models.IntegerField(
                        default=0, help_text="Percentage of pool to reserve (0-100)"
                    ),
                ),
                (
                    "reserved_count",
                    models.IntegerField(default=0, help_text="Fixed number of IPs to reserve"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether the pool is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subnet",
                    models.ForeignKey(
                        help_text="Subnet this pool belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_pools",
                        to="ipam.subnet",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Pool",
                "verbose_name_plural": "IP Pools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NetworkScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("ping", "Ping/ICMP"),
                            ("arp", "ARP"),
                            ("tcp", "TCP Port Scan"),
                            ("full", "Full Scan"),
                        ],
                        default="ping",
                        help_text="Type of scan to perform",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Scan status",
                        max_length=20,
                    ),
                ),
                (
                    "timeout",
                    models.IntegerField(default=3, help_text="Timeout in seconds for each host"),
                ),
                (
                    "max_hosts",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of hosts to scan (null = all)",
                        null=True,
                    ),
                ),
                (
                    "hosts_found",
                    models.IntegerField(default=0, help_text="Number of hosts discovered"),
                ),
                (
                    "hosts_new",
                    models.IntegerField(default=0, help_text="Number of new hosts not in IPAM"),
                ),
                (
                    "hosts_missing",
                    models.IntegerField(
                        default=0, help_text="Number of IPAM hosts not found in scan"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, help_text="When the scan started", null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the scan completed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if scan failed", null=True
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the scan",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="network_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subnet",
                    models.ForeignKey(
                        help_text="Subnet to scan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_scans",
                        to="ipam.subnet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Network Scan",
                "verbose_name_plural": "Network Scans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhoneNumberRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        blank=True, help_text="Telecom carrier/provider", max_length=255, null=True
                    ),
                ),
                (
                    "trunk",
                    models.CharField(
                        blank=True, help_text="Trunk identifier", max_length=255, null=True
                    ),
                ),
                (
                    "start_number",
                    models.CharField(help_text="Starting phone number in the range", max_length=20),
                ),
                (
                    "stop_number",
                    models.CharField(help_text="Ending phone number in the range", max_length=20),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this phone number range",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Location associated with this phone number range",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_number_ranges",
                        to="infrastructure.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phone Number Range",
                "verbose_name_plural": "Phone Number Ranges",
                "ordering": ["start_number"],
            },
        ),
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(help_text="IP address discovered")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the host responded to the scan"
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(
                        blank=True, help_text="Response time in milliseconds", null=True
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True, help_text="MAC address if discovered", max_length=17, null=True
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True, help_text="Hostname if discovered", max_length=255, null=True
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        help_text="Vendor from MAC address lookup",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "in_ipam",
                    models.BooleanField(default=False, help_text="Whether this IP exists in IPAM"),
                ),
                (
                    "ipam_status",
                    models.CharField(
                        blank=True, help_text="Status in IPAM if exists", max_length=20, null=True
                    ),
                ),
                (
                    "open_ports",
                    models.JSONField(
                        blank=True, default=list, help_text="List of open ports if TCP scan"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this host", null=True
                    ),
                ),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.ForeignKey(
                        help_text="Network scan this result belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="ipam.networkscan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan Result",
                "verbose_name_plural": "Scan Results",
                "ordering": ["ip_address"],
            },
        ),
        migrations.AddIndex(
            model_name="dhcpscope",
            index=models.Index(
                fields=["subnet", "is_active"], name="ipam_dhcpsc_subnet__687f78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dhcpscope",
            index=models.Index(
                fields=["start_ip", "end_ip"], name="ipam_dhcpsc_start_i_70671a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dhcpreservation",
            index=models.Index(
                fields=["scope", "is_active"], name="ipam_dhcpre_scope_i_663ea2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dhcpreservation",
            index=models.Index(
                fields=["mac_address", "is_active"], name="ipam_dhcpre_mac_add_aad056_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dhcpreservation",
            unique_together={("scope", "ip_address"), ("scope", "mac_address")},
        ),
        migrations.AddIndex(
            model_name="dhcplease",
            index=models.Index(
                fields=["scope", "status", "-lease_end"], name="ipam_dhcple_scope_i_5b6e21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dhcplease",
            index=models.Index(
                fields=["ip_address", "status"], name="ipam_dhcple_ip_addr_991883_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dhcplease",
            index=models.Index(
                fields=["mac_address", "status"], name="ipam_dhcple_mac_add_ebb0d8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dhcplease",
            unique_together={("scope", "ip_address", "mac_address")},
        ),
        migrations.AddIndex(
            model_name="ippool",
            index=models.Index(
                fields=["subnet", "is_active"], name="ipam_ippool_subnet__b076cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ippool",
            index=models.Index(
                fields=["start_ip", "end_ip"], name="ipam_ippool_start_i_83eeda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="networkscan",
            index=models.Index(
                fields=["subnet", "-created_at"], name="ipam_networ_subnet__2c5dcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="networkscan",
            index=models.Index(
                fields=["status", "-created_at"], name="ipam_networ_status_62cea5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="networkscan",
            index=models.Index(
                fields=["started_by", "-created_at"], name="ipam_networ_started_da402b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phonenumberrange",
            index=models.Index(
                fields=["location", "start_number"], name="ipam_phonen_locatio_9ef113_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phonenumberrange",
            index=models.Index(
                fields=["carrier", "start_number"], name="ipam_phonen_carrier_c96b54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanresult",
            index=models.Index(
                fields=["scan", "ip_address"], name="ipam_scanre_scan_id_04560c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanresult",
            index=models.Index(
                fields=["is_active", "in_ipam"], name="ipam_scanre_is_acti_8a55a3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scanresult",
            unique_together={("scan", "ip_address")},
        ),
    ]
