# Generated by Django 5.2.7 on 2026-01-16 10:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0004_remove_carriercontact_address1_and_more"),
        ("ipam", "0005_dhcpscope_dhcpreservation_dhcplease_ippool_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Device type name (e.g., Switch, Router, Wireless)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this device type", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this device type is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Device Type",
                "verbose_name_plural": "Device Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IPNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Note title (optional)", max_length=255, null=True
                    ),
                ),
                ("content", models.TextField(help_text="Note content (supports markdown/HTML)")),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Whether the note is visible to all users"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False, help_text="Whether the note is pinned to the top"
                    ),
                ),
                ("version", models.IntegerField(default=1, help_text="Note version number")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this note",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ip_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ip_address",
                    models.ForeignKey(
                        help_text="IP address this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="ipam.ipaddress",
                    ),
                ),
                (
                    "parent_note",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent note (for versioning)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="ipam.ipnote",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this note",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_ip_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Note",
                "verbose_name_plural": "IP Notes",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IPNoteAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Attachment file", upload_to="ip_notes/attachments/%Y/%m/%d/"
                    ),
                ),
                ("filename", models.CharField(help_text="Original filename", max_length=255)),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                (
                    "content_type",
                    models.CharField(
                        blank=True, help_text="File content type", max_length=100, null=True
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.ForeignKey(
                        help_text="Note this attachment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="ipam.ipnote",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded this attachment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_ip_note_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Note Attachment",
                "verbose_name_plural": "IP Note Attachments",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="IPNoteComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField(help_text="Comment content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who wrote this comment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ip_note_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        help_text="Note this comment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="ipam.ipnote",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Note Comment",
                "verbose_name_plural": "IP Note Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="IPTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tag name (must be unique)",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tag name can only contain letters, numbers, underscores, and hyphens",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Tag description", null=True),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("red", "Red"),
                            ("yellow", "Yellow"),
                            ("purple", "Purple"),
                            ("orange", "Orange"),
                            ("pink", "Pink"),
                            ("gray", "Gray"),
                            ("indigo", "Indigo"),
                            ("teal", "Teal"),
                        ],
                        default="blue",
                        help_text="Tag color for UI display",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether the tag is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "IP Tag",
                "verbose_name_plural": "IP Tags",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name", "is_active"], name="ipam_iptag_name_369b6a_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="IPAddressTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this tag was applied"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about why this tag was applied",
                        null=True,
                    ),
                ),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who applied this tag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_ip_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ip_address",
                    models.ForeignKey(
                        help_text="IP address this tag is applied to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_address_tags",
                        to="ipam.ipaddress",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="Tag being applied",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_address_tags",
                        to="ipam.iptag",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Address Tag",
                "verbose_name_plural": "IP Address Tags",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.AddField(
            model_name="ipaddress",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags applied to this IP address",
                related_name="ip_addresses",
                through="ipam.IPAddressTag",
                to="ipam.iptag",
            ),
        ),
        migrations.CreateModel(
            name="Rack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Rack name/identifier", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Rack description", null=True),
                ),
                (
                    "total_units",
                    models.PositiveIntegerField(
                        default=42, help_text="Total rack units (U) available"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Location where this rack is located",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="racks",
                        to="infrastructure.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rack",
                "verbose_name_plural": "Racks",
                "ordering": ["location", "name"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Device hostname/name", max_length=255)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Primary IP address (IPv4 or IPv6)", null=True
                    ),
                ),
                (
                    "rack_position",
                    models.PositiveIntegerField(
                        blank=True, help_text="Position in rack (U unit)", null=True
                    ),
                ),
                (
                    "rack_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="Size of device in rack units (U)", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Device description", null=True),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        help_text="Device vendor/manufacturer",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, help_text="Device model", max_length=255, null=True
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, help_text="Device version/firmware", max_length=255, null=True
                    ),
                ),
                (
                    "switch_port",
                    models.CharField(
                        blank=True,
                        choices=[("wired", "Wired"), ("wireless", "Wireless")],
                        help_text="Switch port type",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "sections",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Sections to display device in (e.g., ['servers', 'ipv6'])",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether the device is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Physical location of the device",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="infrastructure.location",
                    ),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of device",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="ipam.devicetype",
                    ),
                ),
                (
                    "rack",
                    models.ForeignKey(
                        blank=True,
                        help_text="Rack where device is mounted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="ipam.rack",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubnetThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "warning_threshold",
                    models.IntegerField(
                        default=75,
                        help_text="Warning threshold percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "critical_threshold",
                    models.IntegerField(
                        default=90,
                        help_text="Critical threshold percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "enable_alerts",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to send alerts when thresholds are exceeded",
                    ),
                ),
                (
                    "alert_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address to send alerts to (if different from subnet owner)",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "notify_on_warning",
                    models.BooleanField(
                        default=True,
                        help_text="Send notification when warning threshold is reached",
                    ),
                ),
                (
                    "notify_on_critical",
                    models.BooleanField(
                        default=True,
                        help_text="Send notification when critical threshold is reached",
                    ),
                ),
                (
                    "notify_on_recovery",
                    models.BooleanField(
                        default=False,
                        help_text="Send notification when utilization drops below threshold",
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        blank=True, help_text="When the threshold was last checked", null=True
                    ),
                ),
                (
                    "last_alert_sent",
                    models.DateTimeField(
                        blank=True, help_text="When the last alert was sent", null=True
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="healthy",
                        help_text="Current threshold status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subnet",
                    models.OneToOneField(
                        help_text="Subnet this threshold applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threshold",
                        to="ipam.subnet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subnet Threshold",
                "verbose_name_plural": "Subnet Thresholds",
            },
        ),
        migrations.CreateModel(
            name="SubnetThresholdAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("recovery", "Recovery"),
                        ],
                        help_text="Type of alert",
                        max_length=20,
                    ),
                ),
                (
                    "utilization_percentage",
                    models.FloatField(help_text="Utilization percentage when alert was triggered"),
                ),
                ("message", models.TextField(help_text="Alert message")),
                (
                    "sent_to",
                    models.EmailField(
                        blank=True,
                        help_text="Email address alert was sent to",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the alert was sent"),
                ),
                (
                    "acknowledged",
                    models.BooleanField(
                        default=False, help_text="Whether the alert has been acknowledged"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, help_text="When the alert was acknowledged", null=True
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who acknowledged the alert",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_threshold_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "threshold",
                    models.ForeignKey(
                        help_text="Threshold that triggered this alert",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="ipam.subnetthreshold",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subnet Threshold Alert",
                "verbose_name_plural": "Subnet Threshold Alerts",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="DHCPOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "option_code",
                    models.IntegerField(db_index=True, help_text="DHCP option code (1-255)"),
                ),
                (
                    "value",
                    models.TextField(help_text="Option value (format depends on option type)"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description for this option", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.ForeignKey(
                        help_text="DHCP scope this option belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="ipam.dhcpscope",
                    ),
                ),
            ],
            options={
                "verbose_name": "DHCP Option",
                "verbose_name_plural": "DHCP Options",
                "ordering": ["scope", "option_code"],
                "indexes": [
                    models.Index(
                        fields=["scope", "option_code"], name="ipam_dhcpop_scope_i_240a51_idx"
                    )
                ],
                "unique_together": {("scope", "option_code")},
            },
        ),
        migrations.CreateModel(
            name="IPAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ip_address_str",
                    models.GenericIPAddressField(
                        help_text="IP address (stored as string for deleted IPs)"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("assigned", "Assigned"),
                            ("released", "Released"),
                            ("status_changed", "Status Changed"),
                            ("description_changed", "Description Changed"),
                            ("subnet_changed", "Subnet Changed"),
                            ("tag_added", "Tag Added"),
                            ("tag_removed", "Tag Removed"),
                            ("note_added", "Note Added"),
                            ("note_updated", "Note Updated"),
                            ("note_deleted", "Note Deleted"),
                        ],
                        help_text="Action performed",
                        max_length=50,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Username (stored for deleted users)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True,
                        help_text="Field that was changed (if applicable)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, help_text="Previous value (if applicable)", null=True
                    ),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, help_text="New value (if applicable)", null=True),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason/justification for the change", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata about the change"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the action was performed"
                    ),
                ),
                (
                    "subnet_id",
                    models.IntegerField(
                        blank=True, help_text="Subnet ID (stored for deleted IPs)", null=True
                    ),
                ),
                (
                    "subnet_network",
                    models.CharField(
                        blank=True,
                        help_text="Subnet network (stored for deleted IPs)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.ForeignKey(
                        blank=True,
                        help_text="IP address this log entry is for",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="ipam.ipaddress",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ip_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Audit Log",
                "verbose_name_plural": "IP Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "-created_at"], name="ipam_ipaudi_ip_addr_30f9f5_idx"
                    ),
                    models.Index(
                        fields=["ip_address_str", "-created_at"],
                        name="ipam_ipaudi_ip_addr_c1d36b_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"], name="ipam_ipaudi_user_id_a1742a_idx"
                    ),
                    models.Index(
                        fields=["action", "-created_at"], name="ipam_ipaudi_action_8547c2_idx"
                    ),
                    models.Index(fields=["created_at"], name="ipam_ipaudi_created_507315_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="IPAuditLogFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Filter name", max_length=255)),
                ("filters", models.JSONField(default=dict, help_text="Filter parameters (JSON)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this filter",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_audit_log_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Audit Log Filter",
                "verbose_name_plural": "IP Audit Log Filters",
                "ordering": ["-updated_at"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="ipnote",
            index=models.Index(
                fields=["ip_address", "-created_at"], name="ipam_ipnote_ip_addr_0c75ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ipnote",
            index=models.Index(
                fields=["ip_address", "-is_pinned"], name="ipam_ipnote_ip_addr_90f505_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ipnote",
            index=models.Index(
                fields=["created_by", "-created_at"], name="ipam_ipnote_created_e34a0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ipnotecomment",
            index=models.Index(
                fields=["note", "created_at"], name="ipam_ipnote_note_id_02b18e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ipaddresstag",
            index=models.Index(fields=["ip_address", "tag"], name="ipam_ipaddr_ip_addr_c0c520_idx"),
        ),
        migrations.AddIndex(
            model_name="ipaddresstag",
            index=models.Index(fields=["tag", "applied_at"], name="ipam_ipaddr_tag_id_cce3af_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="ipaddresstag",
            unique_together={("ip_address", "tag")},
        ),
        migrations.AlterUniqueTogether(
            name="rack",
            unique_together={("name", "location")},
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["name"], name="ipam_device_name_757a05_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["ip_address"], name="ipam_device_ip_addr_ae721f_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["device_type", "is_active"], name="ipam_device_device__5920e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["location", "rack"], name="ipam_device_locatio_cac5a9_idx"),
        ),
        migrations.AddIndex(
            model_name="subnetthreshold",
            index=models.Index(
                fields=["subnet", "current_status"], name="ipam_subnet_subnet__95581f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subnetthreshold",
            index=models.Index(
                fields=["enable_alerts", "current_status"], name="ipam_subnet_enable__8dd80d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subnetthresholdalert",
            index=models.Index(
                fields=["threshold", "-sent_at"], name="ipam_subnet_thresho_b360d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subnetthresholdalert",
            index=models.Index(
                fields=["alert_type", "-sent_at"], name="ipam_subnet_alert_t_fc1125_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subnetthresholdalert",
            index=models.Index(
                fields=["acknowledged", "-sent_at"], name="ipam_subnet_acknowl_ed9bdd_idx"
            ),
        ),
    ]
