# Generated by Django 5.2.7 on 2026-01-21 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipam", "0006_devicetype_ipnote_ipnoteattachment_ipnotecomment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subnet",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Subnet group this subnet belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subnets",
                to="ipam.subnetgroup",
            ),
        ),
    ]
