# Generated by Django 5.2.7 on 2025-11-24 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text="Unique permission identifier (e.g., 'view_monitoring')", max_length=100, unique=True)),
                ('name', models.CharField(help_text="Human-readable permission name (e.g., 'View Monitoring')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this permission allows', null=True)),
                ('app_label', models.CharField(blank=True, help_text="App/module this permission belongs to (e.g., 'monitoring', 'assets')", max_length=100, null=True)),
                ('category', models.CharField(blank=True, help_text="Permission category for grouping (e.g., 'monitoring', 'assets', 'infrastructure')", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this permission is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Permission',
                'verbose_name_plural': 'App Permissions',
                'db_table': 'users_app_permission',
                'ordering': ['category', 'app_label', 'codename'],
                'indexes': [models.Index(fields=['codename'], name='users_app_p_codenam_b2b117_idx'), models.Index(fields=['category', 'app_label'], name='users_app_p_categor_0646e7_idx')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='app_permissions',
            field=models.ManyToManyField(blank=True, help_text='App-level permissions assigned directly to this user', related_name='users', to='users.apppermission'),
        ),
        migrations.CreateModel(
            name='AppPermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, help_text='User who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_group_permissions', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Django Group', on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to='auth.group')),
                ('permission', models.ForeignKey(help_text='App Permission', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='users.apppermission')),
            ],
            options={
                'verbose_name': 'Group App Permission',
                'verbose_name_plural': 'Group App Permissions',
                'db_table': 'users_app_permission_group',
                'indexes': [models.Index(fields=['group', 'permission'], name='users_app_p_group_i_8b7db3_idx')],
                'unique_together': {('group', 'permission')},
            },
        ),
    ]
