# Generated by Django 5.2.7 on 2026-03-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_apppermission_user_app_permissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apppermission",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Permission category for grouping     (e.g., 'monitoring', 'assets', 'infrastructure')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="app_permissions",
            field=models.ManyToManyField(
                blank=True,
                db_table="users_user_app_permissions_many_to_many",
                help_text="App-level permissions assigned directly to this user",
                related_name="users",
                to="users.apppermission",
            ),
        ),
    ]
