# Generated by Django 5.2.7 on 2026-03-18 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_alter_apppermission_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable bundle name (e.g. 'View IPAM')", max_length=100, unique=True)),
                ('code', models.CharField(help_text="Unique code for this bundle (e.g. 'view_ipam', 'edit_monitoring')", max_length=100, unique=True)),
                ('app', models.CharField(blank=True, help_text="Optional app label for filtering in UI (e.g. 'ipam', 'monitoring')", max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this bundle grants', null=True)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Django permissions included in this bundle', related_name='bundles', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Permission Bundle',
                'verbose_name_plural': 'Permission Bundles',
                'db_table': 'users_permission_bundle',
                'ordering': ['app', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ExtendedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(help_text='Django Group this extension belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='extended', to='auth.group')),
                ('bundles', models.ManyToManyField(blank=True, help_text='Permission bundles (subgroups) assigned to this role', related_name='extended_groups', to='users.permissionbundle')),
            ],
            options={
                'verbose_name': 'Extended Group',
                'verbose_name_plural': 'Extended Groups',
                'db_table': 'users_extended_group',
            },
        ),
    ]
