# Generated by Django 5.2.7 on 2026-03-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_permission_bundles_and_extended_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="app_permissions",
        ),
        # Delete AppPermissionGroup first (it has FKs to AppPermission and User)
        migrations.DeleteModel(
            name="AppPermissionGroup",
        ),
        migrations.DeleteModel(
            name="AppPermission",
        ),
    ]
