# Data migration: create users_user_groups and users_user_user_permissions
# if they are missing (e.g. DB was restored or tables were dropped).
# Safe to run: uses IF NOT EXISTS.

from django.db import migrations


def create_m2m_tables_if_missing(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as cursor:
        # PostgreSQL: create users_user_groups if missing (User <-> Group M2M)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS users_user_groups (
                id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                user_id bigint NOT NULL,
                group_id integer NOT NULL,
                CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id)
            );
        """)
        cursor.execute("""
            DO $$ BEGIN
                ALTER TABLE users_user_groups ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id
                FOREIGN KEY (user_id) REFERENCES users_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;
        """)
        cursor.execute("""
            DO $$ BEGIN
                ALTER TABLE users_user_groups ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id
                FOREIGN KEY (group_id) REFERENCES auth_group(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;
        """)
        cursor.execute("CREATE INDEX IF NOT EXISTS users_user_groups_user_id_5f6f5a90 ON users_user_groups (user_id);")
        cursor.execute("CREATE INDEX IF NOT EXISTS users_user_groups_group_id_9afc8d0e ON users_user_groups (group_id);")

        # PostgreSQL: create users_user_user_permissions if missing (User <-> Permission M2M)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS users_user_user_permissions (
                id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                user_id bigint NOT NULL,
                permission_id integer NOT NULL,
                CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id)
            );
        """)
        cursor.execute("""
            DO $$ BEGIN
                ALTER TABLE users_user_user_permissions ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id
                FOREIGN KEY (user_id) REFERENCES users_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;
        """)
        cursor.execute("""
            DO $$ BEGIN
                ALTER TABLE users_user_user_permissions ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm
                FOREIGN KEY (permission_id) REFERENCES auth_permission(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;
        """)
        cursor.execute("CREATE INDEX IF NOT EXISTS users_user_user_permissions_user_id_20aca447 ON users_user_user_permissions (user_id);")
        cursor.execute("CREATE INDEX IF NOT EXISTS users_user_user_permissions_permission_id_0b93982e ON users_user_user_permissions (permission_id);")


def noop_reverse(apps, schema_editor):
    # Do not drop tables on reverse; they are required for User model.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_app_permissions_and_more"),
    ]

    operations = [
        migrations.RunPython(create_m2m_tables_if_missing, noop_reverse),
    ]
