# Generated by Django 5.2.7 on 2026-02-05 08:44

import contracts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="Contract document (PDF, DOC, etc.). Max 10 MB. Stored with a safe filename.",
                null=True,
                upload_to=contracts.validators.contract_document_upload_to,
                validators=[
                    contracts.validators.validate_contract_file_extension,
                    contracts.validators.validate_contract_file_size,
                ],
            ),
        ),
    ]
