# Generated by Django 5.2.7 on 2026-02-13 11:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0004_remove_carriercontact_address1_and_more'),
        ('telecom', '0005_phonenumber_service_to_service_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('extension_number', models.CharField(blank=True, help_text='Internal extension (1 to 10 digits).', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Extension number must be 1 to 10 digits.', regex='^\\d{1,10}$')])),
                ('service_type', models.CharField(choices=[('fax', 'Fax'), ('ivr', 'IVR'), ('ring_group', 'Ring Group'), ('forwarder', 'Forwarder'), ('extension', 'Extension')], max_length=20)),
                ('did_enabled', models.BooleanField(default=False, help_text='If enabled, this external number can be dialed internally (DID).')),
                ('did_external_number', models.CharField(blank=True, help_text='Optional external DID number mapped to this record.', max_length=32, null=True)),
                ('is_static_assignment', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_phone_numbers', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_phone_numbers', to='infrastructure.location')),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management_record', to='telecom.phonenumber')),
            ],
            options={
                'verbose_name': 'Managed Phone Number',
                'verbose_name_plural': 'Managed Phone Numbers',
                'ordering': ['location__name', 'name', 'phone_number__number'],
                'indexes': [models.Index(fields=['location', 'service_type'], name='phone_manag_locatio_c2313b_idx'), models.Index(fields=['extension_number'], name='phone_manag_extensi_ce178f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ManagedPhoneNumberBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_number', models.CharField(max_length=32)),
                ('end_number', models.CharField(max_length=32)),
                ('is_static_assignment', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_phone_number_blocks', to='infrastructure.location')),
            ],
            options={
                'verbose_name': 'Managed Phone Number Block',
                'verbose_name_plural': 'Managed Phone Number Blocks',
                'ordering': ['location__name', 'start_number'],
                'indexes': [models.Index(fields=['location', 'start_number', 'end_number'], name='phone_manag_locatio_f310ce_idx')],
            },
        ),
    ]
