# Generated by Django 5.2.7

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_phone_number_to_number(apps, schema_editor):
    ManagedPhoneNumber = apps.get_model("phone_management", "ManagedPhoneNumber")
    for rec in ManagedPhoneNumber.objects.select_related("phone_number").all():
        if rec.phone_number_id:
            rec.number = rec.phone_number.number
            rec.save(update_fields=["number"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0004_remove_carriercontact_address1_and_more"),
        ("telecom", "0005_phonenumber_service_to_service_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("phone_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedphonenumber",
            name="number",
            field=models.CharField(
                help_text="Phone number (e.g. +1-312-273-2048 or E.164).",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="managedphonenumber",
            name="custom_field_1",
            field=models.CharField(
                blank=True,
                help_text="Optional field; meaning depends on service type.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="managedphonenumber",
            name="custom_field_2",
            field=models.CharField(
                blank=True,
                help_text="Optional field; meaning depends on service type.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.RunPython(copy_phone_number_to_number, noop_reverse),
        migrations.RemoveField(
            model_name="managedphonenumber",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="managedphonenumber",
            name="number",
            field=models.CharField(
                help_text="Phone number (e.g. +1-312-273-2048 or E.164).",
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AlterModelOptions(
            name="managedphonenumber",
            options={
                "ordering": ["location__name", "name", "number"],
                "verbose_name": "Managed Phone Number",
                "verbose_name_plural": "Managed Phone Numbers",
            },
        ),
        migrations.AddIndex(
            model_name="managedphonenumber",
            index=models.Index(fields=["number"], name="phone_manag_number_8a2b14_idx"),
        ),
    ]
