# Generated by Django 5.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phone_management", "0002_move_number_to_phone_management"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="managedphonenumber",
            name="custom_field_1",
        ),
        migrations.RemoveField(
            model_name="managedphonenumber",
            name="custom_field_2",
        ),
    ]
