# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone_management", "0003_remove_managedphonenumber_custom_field_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedphonenumber",
            name="service_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Task-specific config: IVR (welcome_message, menu, timeout), Fax (retry_count), Ring Group (member_extensions, strategy), Forwarder (destination).",
            ),
        ),
    ]
