# Generated by Django 5.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phone_management", "0004_add_service_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="managedphonenumber",
            name="service_config",
        ),
    ]
