# Generated by Django 5.2.7 on 2026-02-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phone_management", "0005_remove_managedphonenumber_service_config"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="managedphonenumber",
            new_name="phone_manag_number_2d83bf_idx",
            old_name="phone_manag_number_8a2b14_idx",
        ),
    ]
