# Generated by Django 5.2.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannelConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slack_enabled", models.BooleanField(default=False)),
                ("slack_webhook_url", models.URLField(blank=True, max_length=2000)),
                ("slack_default_channel", models.CharField(blank=True, max_length=255)),
                ("discord_enabled", models.BooleanField(default=False)),
                ("discord_webhook_url", models.URLField(blank=True, max_length=2000)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="If null, this is the system-wide default config.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_channel_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification channel config",
                "verbose_name_plural": "Notification channel configs",
            },
        ),
    ]
