# Generated by Django (model rename)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NotificationChannelConfig",
            new_name="NotificationConfig",
        ),
    ]
