# Generated by Django 5.2.7 on 2026-02-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_notificationreadreceipt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationconfig",
            options={
                "verbose_name": "Notification config",
                "verbose_name_plural": "Notification configs",
            },
        ),
    ]
