# Generated by Django 5.2.7 on 2026-03-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_notificationconfig_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationconfig",
            name="email_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationconfig",
            name="email_recipient",
            field=models.CharField(
                blank=True,
                help_text="Default recipient email for tests and system alerts",
                max_length=255,
            ),
        ),
    ]
