# Generated by Django 5.2.7 on 2026-03-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_notificationconfig_email_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationconfig",
            name="sms_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationconfig",
            name="sms_recipient",
            field=models.CharField(
                blank=True,
                help_text="Default recipient phone number (E.164, e.g. +15551234567) for SMS tests and alerts",
                max_length=64,
            ),
        ),
    ]
