# Generated by Django 5.2.7 on 2025-12-27 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0004_remove_carriercontact_address1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, choices=[('voice', 'Voice'), ('data', 'Data'), ('internet', 'Internet'), ('mobile', 'Mobile'), ('consolidated', 'Consolidated')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, help_text='URL to provider logo', null=True)),
                ('monthly_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly cost in dollars', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_id', models.CharField(blank=True, help_text='Primary circuit identifier', max_length=255, null=True)),
                ('alternate_cid', models.CharField(blank=True, help_text='Alternate circuit identifier', max_length=255, null=True)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('security_code', models.CharField(blank=True, max_length=255, null=True)),
                ('circuit_type', models.CharField(blank=True, choices=[('broadband', 'Broadband'), ('dia', 'DIA'), ('satellite', 'Satellite'), ('lte_wireless', 'LTE Wireless'), ('ptp_wireless', 'PTP Wireless'), ('mpls', 'MPLS')], max_length=20, null=True)),
                ('line_speed', models.CharField(blank=True, choices=[('10_mbps', '10 Mb/s'), ('100_mbps', '100 Mb/s'), ('1_gbps', '1Gb/s'), ('10_gbps', '10Gb/s'), ('100_gbps', '100Gb/s')], max_length=20, null=True)),
                ('port_speed', models.CharField(blank=True, max_length=255, null=True)),
                ('handoff_type', models.CharField(blank=True, choices=[('copper', 'Copper'), ('fiber', 'Fiber')], max_length=20, null=True)),
                ('fiber_type', models.CharField(blank=True, choices=[('multimode', 'Multimode'), ('singlemode', 'Singlemode')], max_length=20, null=True)),
                ('connector_type', models.CharField(blank=True, choices=[('st', 'ST'), ('sc', 'SC'), ('lc', 'LC')], max_length=20, null=True)),
                ('quote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_id', models.CharField(blank=True, max_length=255, null=True)),
                ('foc_date', models.DateField(blank=True, help_text='FOC (Firm Order Commitment) Date', null=True)),
                ('ttu_date', models.DateField(blank=True, help_text='TTU (Turn Up) Date', null=True)),
                ('monthly_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly cost in dollars', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_circuits', to='infrastructure.location')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_circuits', to='telecom.provider')),
            ],
            options={
                'verbose_name': 'Data Circuit',
                'verbose_name_plural': 'Data Circuits',
                'ordering': ['circuit_id', 'carrier'],
            },
        ),
    ]
