# Generated by Django 5.2.7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0004_remove_carriercontact_address1_and_more"),
        ("telecom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Phone number (e.g. +1-312-273-2048 or E.164)",
                        max_length=32,
                    ),
                ),
                (
                    "friendly_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telecom_phone_numbers",
                        to="infrastructure.location",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_numbers",
                        to="telecom.provider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        help_text="Associated data/voice service (circuit)",
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_numbers",
                        to="telecom.datacircuit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phone Number",
                "verbose_name_plural": "Phone Numbers",
                "ordering": ["number"],
            },
        ),
    ]
