# Generated by Django 5.2.7 on 2026-02-28 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telecom", "0005_phonenumber_service_to_service_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated business service",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="phone_numbers",
                to="telecom.service",
            ),
        ),
    ]
